name: image_classification_mobilenet
description: Image Classification using mobilenet.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  #used google fonts
  google_fonts: ^6.1.0

  #adding firebase functionality
  firebase_core: ^2.25.4

  #firebase's database
  cloud_firestore: ^4.15.4

  #getx state management
  get: ^4.6.6

  #for user's authentication
  firebase_auth: ^4.17.4

  #getting files from system
  file_picker: ^6.1.1

  #for storing docs
  firebase_storage: ^11.6.6

  #preview image
  photo_view: ^0.14.0
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  camera: ^0.10.5+2
  flutter:
    sdk: flutter
  image: ^4.0.17
  path: ^1.8.3
  path_provider: ^2.0.15
  image_picker: ^1.1.0
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.4
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/logos/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
